### ISSUE TITLE
Broken with influx 0.10

### ISSUE THREAD

**Issue by Bolik** [unbit/uwsgi-influxdb#2]
After starting there are tons of messages like this:

Mon Feb 15 17:05:42 2016 - [influxdb] HTTP api returned non-200 response code for rss_size: 400
{"error":"json: cannot unmarshal array into Go value of type struct { Points []client.Point \"json:\\"points\\"\"; Database string \"json:\\"database\\"\"; RetentionPolicy string \"json:\\"retentionPolicy\\"\"; Tags map[string]string \"json:\\"tags\\"\"; Time time.Time \"json:\\"time\\"\"; Precision string \"json:\\"precision\\"\" }"}

**Comment by blaggacao** [comment]
[Influx deprecated json](https://docs.influxdata.com/influxdb/v0.13/write_protocols/json/) format. It was replaced by the line format

This plugin uses json: https://github.com/unbit/uwsgi-influxdb/blob/master/plugin.c#L19

Useless :cry: 

Options that come to my mind would be:
- Use the statsd uwsgi plugin and catch it with [StatsD influx telegraf endpint](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/statsd) Who knows if they are compatible...
- Use the telegraf snmp input plugin and the uwsgi snmp server (awful to configure and maintain with all those OID)
- Help out with the development of an uwsgi plugin for telegraf, which got stuck: https://github.com/influxdata/telegraf/pull/1028
- EDIT: Configure uwsgi with graphite and make influxdb listen on it's graphite endpoint. Happy templating!
- EDIT2: If you only care about numbers, you can query the uwsgi stats server directly with https://github.com/influxdata/telegraf/tree/master/plugins/inputs/httpjson

It's pest or cholera.
